remote_theme: pmarsceill/just-the-docs
title: 401 Docs
description: Documentation for FRC Team 401
search_enabled: true
color_scheme: "dark"
aux_links:
  "401 Docs on GitHub":
    - "//github.com/team401/Docs"
    
markdown: kramdown
kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
