site_name: Docs
site_url: https://team401.github.io/Docs
site_description: "FIRST Robotics Competition documentation developed by \nFRC Team 401: Copperhead Robotics"

repo_url: https://github.com/team401/Docs
edit_uri: edit/main/docs/

extra_css:
  - stylesheets/colors.css
theme:
  name: material
  favicon: images/logo_sq.png
  logo: images/logo.png
  palette:
    # Light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to Dark Mode

    # Dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Light Mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    # - navigation.tabs
    # - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.footer
    - toc.follow

    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select

validation:
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn

markdown_extensions:
  - toc:
      permalink: ""
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: Copyright &copy; FRC Team 401 2025
extra:
  generator: false
  social:
    - icon: material/email-box
      link: mailto:team401@mcps.org
    - icon: simple/github
      link: https://github.com/team401
    - icon: simple/instagram
      link: https://instagram.com/team401
    - icon: simple/facebook
      link: https://www.facebook.com/copperheadrobotics/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/frcteam401
    - icon: simple/youtube
      link: https://www.youtube.com/@FRCTeam401CopperheadRobotics

plugins:
  - search
  - group:
      enabled: !ENV CI
      plugins:
        - social:
            cards_layout_options:
              background_color: "#d35401"
  - git-revision-date-localized:
      enable_creation_date: true
