site_name: Docs
site_url: https://team401.github.io
site_description: "FIRST Robotics Competition documentation developed by \nFRC Team 401: Copperhead Robotics"

repo_url: https://github.com/team401/Docs
edit_uri: edit/main/docs/

extra_css:
  - stylesheets/colors.css
theme:
  name: material
  favicon: images/logo_sq.png
  logo: images/logo.png
  palette:
    # Light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to Dark Mode

    # Dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Light Mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    # - navigation.tabs
    # - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.footer
    - toc.follow

    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select

validation:
  links:
    absolute_links: relative_to_docs

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: ""

extra:
  generator: false

plugins:
  - search
  - group:
      enabled: !ENV CI
      plugins:
        - social:
            cards_layout_options:
              background_color: "#d35401"
  - git-revision-date-localized:
      enable_creation_date: true
